// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tylixjayqdjsrqvqrpno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bGl4amF5cWRqc3JxdnFycG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDIwODgsImV4cCI6MjA2NjMxODA4OH0.vncmUmriX2xqtqHRC_nQUvIxPhu8DTRSgMd1jqKzQXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);