// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmzjfishvuidotbairty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tempmaXNodnVpZG90YmFpcnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDQwNjAsImV4cCI6MjA2NjI4MDA2MH0.XavUgv5MjiStDFDscRcqK0diZ5QrdIiXaVsno16ZZOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);